spring:
  datasource:
    url: jdbc:mysql://localhost:3306/address1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

